server.port=8081

spring.application.name=bolsa-trabajos

spring.datasource.url=jdbc:mysql://localhost:3306/bolsa_trabajos

spring.datasource.username=root

spring.datasource.password=mysql

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
